import { ConsultationMode } from "@/app/api/appointment/props";
import { ReferralDto, ReferralStatus, ReferralPriority, ReferralType } from "@/app/api/referral/props";

export const mockReferrals: ReferralDto[] = [
    {
        id: "1",
        referralNumber: "REF-2024-001",
        referringDoctor: {
            id: "doc1",
            name: "Dr. Sarah Johnson",
            email: "sarah.johnson@mytelmed.com",
            phone: "+65 9123 4567",
            specialityList: ["Cardiology", "Internal Medicine"],
            facility: {
                id: "fac1",
                name: "MyTelmed Medical Center",
                address: "123 Healthcare Street, Singapore 123456",
                telephone: "+65 9123 4567",
                city: "Singapore",
                state: "Singapore",
                facilityType: "HOSPITAL",
                thumbnailUrl: "https://via.placeholder.com/150",
            },
        },
        referredDoctor: {
            id: "doc2",
            name: "Dr. Michael Chen",
            email: "michael.chen@mytelmed.com",
            phone: "+65 9234 5678",
            specialityList: ["Cardiology"],
            facility: {
                id: "fac2",
                name: "MyTelmed Cardiology Clinic",
                address: "456 Heart Avenue, Singapore 234567",
                telephone: "+65 9123 4567",
                city: "Singapore",
                state: "Singapore",
                facilityType: "CLINIC",
                thumbnailUrl: "https://via.placeholder.com/150",
            },
        },
        referralType: ReferralType.INTERNAL,
        status: ReferralStatus.ACCEPTED,
        priority: ReferralPriority.URGENT,
        clinicalSummary:
            "Patient presents with chest pain and shortness of breath. ECG shows ST elevation. Requires immediate cardiology consultation.",
        reasonForReferral: "Chest Pain Evaluation",
        expiryDate: "2024-12-31T23:59:59Z",
        createdAt: "2024-01-15T10:30:00Z",
        investigationsDone: "ECG, Troponin levels, Chest X-ray",
        currentMedications: "Aspirin 100mg daily, Metoprolol 25mg twice daily",
        allergies: "Penicillin",
        vitalSigns: "BP: 140/90, HR: 95, Temp: 37.2°C",
        notes: "Patient has family history of heart disease. Father had MI at age 45.",
    },
    {
        id: "2",
        referralNumber: "REF-2024-002",
        referringDoctor: {
            id: "doc1",
            name: "Dr. Sarah Johnson",
            email: "sarah.johnson@mytelmed.com",
            phone: "+65 9123 4567",
            specialityList: ["General Practice"],
            facility: {
                id: "fac1",
                name: "MyTelmed Medical Center",
                address: "123 Healthcare Street, Singapore 123456",
                telephone: "+65 9123 4567",
                city: "Singapore",
                state: "Singapore",
                facilityType: "HOSPITAL",
                thumbnailUrl: "https://via.placeholder.com/150",
            },
        },
        referralType: ReferralType.EXTERNAL,
        status: ReferralStatus.PENDING,
        priority: ReferralPriority.ROUTINE,
        clinicalSummary: "Patient with persistent lower back pain for 3 months. Conservative treatment ineffective.",
        reasonForReferral: "Lower Back Pain",
        expiryDate: "2024-11-30T23:59:59Z",
        createdAt: "2024-01-10T14:20:00Z",
        externalDoctorName: "Dr. James Wong",
        externalDoctorSpeciality: "Orthopedics",
        externalFacilityName: "Singapore Orthopedic Center",
        externalFacilityAddress: "789 Spine Road, Singapore 345678",
        externalContactNumber: "+65 9345 6789",
        externalEmail: "james.wong@soc.com.sg",
        investigationsDone: "Lumbar X-ray, MRI L-spine",
        currentMedications: "Ibuprofen 400mg as needed",
        allergies: "None known",
        vitalSigns: "BP: 120/80, HR: 72, Temp: 36.8°C",
        notes: "Patient works as a delivery driver. Pain worse with prolonged sitting.",
    },
    {
        id: "3",
        referralNumber: "REF-2024-003",
        referringDoctor: {
            id: "doc3",
            name: "Dr. Emily Tan",
            email: "emily.tan@mytelmed.com",
            phone: "+65 9456 7890",
            specialityList: ["Pediatrics"],
            facility: {
                id: "fac3",
                name: "MyTelmed Children's Clinic",
                address: "321 Kids Lane, Singapore 456789",
                telephone: "+65 9123 4567",
                city: "Singapore",
                state: "Singapore",
                facilityType: "CLINIC",
                thumbnailUrl: "https://via.placeholder.com/150",
            },
            languageList: ["English", "Mandarin"],
            qualifications: "MBBS, Pediatric Residency",
            dateOfBirth: "1980-05-15",
            gender: "Female",
            nric: "S1234567A",
            enabled: true,
            createdAt: "2024-01-25T14:00:00Z",
            updatedAt: "2024-01-25T14:00:00Z",
        },
        referredDoctor: {
            id: "doc4",
            name: "Dr. David Lim",
            email: "david.lim@mytelmed.com",
            phone: "+65 9567 8901",
            specialityList: ["Pediatric Neurology"],
            facility: {
                id: "fac4",
                name: "MyTelmed Neurology Center",
                address: "654 Brain Street, Singapore 567890",
                telephone: "+65 9123 4567",
                city: "Singapore",
                state: "Singapore",
                facilityType: "CLINIC",
                thumbnailUrl: "https://via.placeholder.com/150",
            },
            languageList: ["English", "Mandarin"],
            qualifications: "MBBS, Pediatric Residency",
            dateOfBirth: "1980-05-15",
            gender: "Female",
            nric: "S1234567A",
            enabled: true,
            createdAt: "2024-01-25T14:00:00Z",
            updatedAt: "2024-01-25T14:00:00Z",
        },
        referralType: ReferralType.INTERNAL,
        status: ReferralStatus.SCHEDULED,
        priority: ReferralPriority.URGENT,
        clinicalSummary: "8-year-old child with recurrent seizures. First episode 2 weeks ago.",
        reasonForReferral: "Seizure Evaluation",
        expiryDate: "2024-12-15T23:59:59Z",
        createdAt: "2024-01-12T09:15:00Z",
        scheduledAppointment: {
            id: "apt1",
            appointmentDateTime: "2024-01-25T14:00:00Z",
            status: "CONFIRMED",
            consultationMode: ConsultationMode.PHYSICAL,
            durationMinutes: 30,
            patientNotes: "Patient is feeling better",
            doctorNotes: "Patient is feeling better",
            reasonForVisit: "Seizure Evaluation",
            cancellationReason: "None",
            completedAt: "2024-01-25T14:30:00Z",
            attachedDocuments: [],
            createdAt: "2024-01-25T14:00:00Z",
            updatedAt: "2024-01-25T14:00:00Z",
            patient: {
                id: "pat1",
                name: "John Doe",
                email: "john.doe@mytelmed.com",
                phone: "+65 9123 4567",
                serialNumber: "1234567890",
                dateOfBirth: "1990-01-01",
                gender: "Male",
                nric: "S1234567A",
                enabled: true,
                createdAt: "2024-01-25T14:00:00Z",
                updatedAt: "2024-01-25T14:00:00Z",
            },
            doctor: {
                id: "doc1",
                name: "Dr. Sarah Johnson",
                email: "sarah.johnson@mytelmed.com",
                phone: "+65 9123 4567",
                specialityList: ["General Practice"],
                facility: {
                    id: "fac1",
                    name: "MyTelmed Medical Center",
                    address: "123 Healthcare Street, Singapore 123456",
                },
            },
        },
        investigationsDone: "EEG, Brain MRI",
        currentMedications: "None",
        allergies: "None known",
        vitalSigns: "BP: 90/60, HR: 88, Temp: 37.0°C",
        notes: "Family history of epilepsy in maternal grandmother.",
    },
    {
        id: "4",
        referralNumber: "REF-2024-004",
        referringDoctor: {
            id: "doc1",
            name: "Dr. Sarah Johnson",
            email: "sarah.johnson@mytelmed.com",
            phone: "+65 9123 4567",
            specialityList: ["General Practice"],
            facility: {
                id: "fac1",
                name: "MyTelmed Medical Center",
                address: "123 Healthcare Street, Singapore 123456",
            },
        },
        referralType: ReferralType.INTERNAL,
        status: ReferralStatus.COMPLETED,
        priority: ReferralPriority.ROUTINE,
        clinicalSummary: "Annual diabetes review. Patient well-controlled on current medication.",
        reasonForReferral: "Diabetes Management",
        expiryDate: "2024-10-31T23:59:59Z",
        createdAt: "2024-01-05T11:45:00Z",
        referredDoctor: {
            id: "doc5",
            name: "Dr. Lisa Wang",
            email: "lisa.wang@mytelmed.com",
            phone: "+65 9678 9012",
            specialityList: ["Endocrinology"],
            facility: {
                id: "fac5",
                name: "MyTelmed Endocrinology Clinic",
                address: "987 Sugar Road, Singapore 678901",
            },
        },
        investigationsDone: "HbA1c, Fasting glucose, Lipid profile",
        currentMedications: "Metformin 500mg twice daily, Gliclazide 80mg daily",
        allergies: "None known",
        vitalSigns: "BP: 130/85, HR: 75, Temp: 36.9°C",
        notes: "Patient lost 5kg in last 6 months through diet and exercise.",
    },
    {
        id: "5",
        referralNumber: "REF-2024-005",
        referringDoctor: {
            id: "doc6",
            name: "Dr. Robert Lee",
            email: "robert.lee@mytelmed.com",
            phone: "+65 9789 0123",
            specialityList: ["Emergency Medicine"],
            facility: {
                id: "fac6",
                name: "MyTelmed Emergency Department",
                address: "147 Emergency Way, Singapore 789012",
            },
        },
        referralType: ReferralType.EXTERNAL,
        status: ReferralStatus.REJECTED,
        priority: ReferralPriority.EMERGENCY,
        clinicalSummary: "Patient with severe abdominal pain and signs of peritonitis.",
        reasonForReferral: "Acute Abdomen",
        expiryDate: "2024-01-20T23:59:59Z",
        createdAt: "2024-01-18T16:30:00Z",
        externalDoctorName: "Dr. Amanda Ng",
        externalDoctorSpeciality: "General Surgery",
        externalFacilityName: "Singapore General Hospital",
        externalFacilityAddress: "1 Hospital Drive, Singapore 169608",
        externalContactNumber: "+65 6222 3322",
        externalEmail: "amanda.ng@sgh.com.sg",
        rejectionReason: "Hospital at full capacity. Please try National University Hospital.",
        investigationsDone: "CT abdomen, Blood tests",
        currentMedications: "IV antibiotics, Pain relief",
        allergies: "None known",
        vitalSigns: "BP: 110/70, HR: 110, Temp: 38.5°C",
        notes: "Patient requires immediate surgical intervention.",
    },
    {
        id: "6",
        referralNumber: "REF-2024-006",
        referringDoctor: {
            id: "doc1",
            name: "Dr. Sarah Johnson",
            email: "sarah.johnson@mytelmed.com",
            phone: "+65 9123 4567",
            specialityList: ["General Practice"],
            facility: {
                id: "fac1",
                name: "MyTelmed Medical Center",
                address: "123 Healthcare Street, Singapore 123456",
            },
        },
        referralType: ReferralType.INTERNAL,
        status: ReferralStatus.EXPIRED,
        priority: ReferralPriority.ROUTINE,
        clinicalSummary: "Patient with chronic knee pain. Previous physiotherapy ineffective.",
        reasonForReferral: "Knee Pain Assessment",
        expiryDate: "2024-01-01T23:59:59Z",
        createdAt: "2023-12-15T10:00:00Z",
        referredDoctor: {
            id: "doc7",
            name: "Dr. Thomas Koh",
            email: "thomas.koh@mytelmed.com",
            phone: "+65 9890 1234",
            specialityList: ["Orthopedics"],
            facility: {
                id: "fac7",
                name: "MyTelmed Orthopedic Center",
                address: "258 Joint Street, Singapore 890123",
            },
        },
        investigationsDone: "Knee X-ray, MRI knee",
        currentMedications: "Paracetamol 500mg as needed",
        allergies: "None known",
        vitalSigns: "BP: 125/80, HR: 70, Temp: 36.7°C",
        notes: "Patient is a retired teacher. Pain worse with stairs and walking.",
    },
    {
        id: "7",
        referralNumber: "REF-2024-007",
        referringDoctor: {
            id: "doc8",
            name: "Dr. Maria Rodriguez",
            email: "maria.rodriguez@mytelmed.com",
            phone: "+65 9901 2345",
            specialityList: ["Dermatology"],
            facility: {
                id: "fac8",
                name: "MyTelmed Dermatology Clinic",
                address: "369 Skin Avenue, Singapore 901234",
            },
        },
        referralType: ReferralType.INTERNAL,
        status: ReferralStatus.CANCELLED,
        priority: ReferralPriority.ROUTINE,
        clinicalSummary: "Patient with suspicious skin lesion on right forearm.",
        reasonForReferral: "Skin Lesion Evaluation",
        expiryDate: "2024-12-31T23:59:59Z",
        createdAt: "2024-01-20T13:45:00Z",
        referredDoctor: {
            id: "doc9",
            name: "Dr. Peter Zhang",
            email: "peter.zhang@mytelmed.com",
            phone: "+65 9012 3456",
            specialityList: ["Dermatology", "Mohs Surgery"],
            facility: {
                id: "fac9",
                name: "MyTelmed Advanced Dermatology",
                address: "741 Mole Road, Singapore 012345",
            },
        },
        investigationsDone: "Skin biopsy",
        currentMedications: "None",
        allergies: "None known",
        vitalSigns: "BP: 118/75, HR: 68, Temp: 36.6°C",
        notes: "Patient cancelled due to personal reasons. Will reschedule.",
    },
];
