export const states = ["Selangor", "Kuala Lumpur", "Putrajaya"];

export const stateAbbreviations: Record<string, string> = {
  Selangor: "SGR",
  KualaLumpur: "KL",
  Putrajaya: "PJY",
};

export const citiesByState: Record<string, string[]> = {
  Selangor: [
    "Ampang",
    "Ampang Jaya",
    "Bagan Nakhoda Omar",
    "Bandar Baru Bangi",
    "Bandar Mahkota Cheras",
    "Bandar Puchong Jaya",
    "Bandar Puncak Alam",
    "Banting",
    "Batang Berjuntal",
    "Batang Kali",
    "Batu Arang",
    "Batu Caves",
    "Behrang Stesen",
    "Bentong",
    "Beranang",
    "Bestari Jaya",
    "Broga",
    "Bukit Fraser",
    "Bukit Rotan",
    "Cheras",
    "Country Heights",
    "Cyberjaya",
    "Damansara Damai",
    "Dengkil",
    "Dusun Tua",
    "Endah",
    "Enstek",
    "Genting Highlands",
    "Gumut",
    "Hulu Langat",
    "Ijok",
    "Janda Baik",
    "Jenjarom",
    "Jeram",
    "Jugra",
    "Kajang",
    "Kalumpang",
    "Kampung Bagan Lalang",
    "Kampung Batu Batu",
    "Kampung Batu Belah",
    "Kampung Daching",
    "Kampung Dusun Tua Seberang",
    "Kampung Hutan Melintang",
    "Kampung India",
    "Kampung Jawa",
    "Kampung Jawa Tengah",
    "Kampung Jelebu",
    "Kampung Kelawar",
    "Kampung Kuala Pajam",
    "Kampung Kubang Beras",
    "Kampung Labohan Dagang",
    "Kampung Lubuk Kelubi",
    "Kampung Panchang Bedena",
    "Kampung Parit Baru Baroh",
    "Kampung Parit Serong",
    "Kampung Paya",
    "Kampung Rinching Ulu",
    "Kampung Salak",
    "Kampung Salak Tinggi",
    "Kampung Sekendi",
    "Kampung Selayang Pandang",
    "Kampung Sesapan Batu Minangkabau",
    "Kampung Sungai Apong",
    "Kampung Sungai Buah",
    "Kampung Sungai Burong",
    "Kampung Sungai Chinchin",
    "Kampung Sungai Gatal",
    "Kampung Sungai Jai",
    "Kampung Sungai Kajang",
    "Kampung Sungai Kembong Hilir",
    "Kampung Sungai Kembong Ulu Bangi",
    "Kampung Sungai Lalang",
    "Kampung Sungai Lang",
    "Kampung Sungai Panjang",
    "Kampung Sungai Pening",
    "Kampung Sungai Rinching",
    "Kampung Sungai Tengar",
    "Kampung Tangkas",
    "Kampung Tanjong Buloh",
    "Kampung Teluk Rhu",
    "Kanching",
    "Kapar",
    "Kerling",
    "Klang",
    "Kota Warisan",
    "Kuala Kubu Bharu",
    "Kuala Lumpur",
    "Kuala Selangor",
    "Labu",
    "Lenggeng",
    "Mantin",
    "Meru",
    "Morib",
    "Nilai",
    "Pasir Penambang",
    "Pelabuhan Klang",
    "Permatang",
    "Petaling Jaya",
    "Port Dickson",
    "Puchong",
    "Pulau Carey",
    "Pulau Ketam",
    "Putrajaya",
    "Rantau Panjang",
    "Rasa",
    "Raub",
    "Rawang",
    "Sabak",
    "Sabak Bernam",
    "Sekinchan",
    "Selekoh",
    "Semenyih",
    "Sepang",
    "Serdang",
    "Serendah",
    "Seri Kembangan",
    "Shah Alam",
    "Slim River",
    "Subang Jaya",
    "Sungai Air Tawar",
    "Sungai Besar",
    "Sungai Buloh",
    "Sungai Gulang Gulang",
    "Sungai Kandis",
    "Sungai Pelek",
    "Sungai Sekamat",
    "Sungai Tengi Kanan",
    "Taman Bukit Permai",
    "Taman Melawati",
    "Taman Muhibah",
    "Taman Mulia Jaya",
    "Taman Murni 2",
    "Taman Paya Jaras Permai",
    "Taman Seri Gombak",
    "Tanjung Karang",
    "Tanjung Malim",
    "Tanjung Sepat",
    "Tasek Permai",
    "Teluk Panglima Garang",
    "Teras",
    "Teras Jernang",
  ],
  KualaLumpur: ["Kuala Lumpur"],
  Putrajaya: ["Putrajaya"],
};
