import { Appointment } from "../../props";

// Static dummy appointments data with variety
const dummyAppointments: Appointment[] = [
  // Upcoming appointments
  {
    id: "apt-001",
    doctorId: 1,
    doctorName: "Dr. Ahmad Razak",
    doctorSpecialty: "Cardiology",
    doctorImage: "/doctor1.jpg",
    facilityId: 1,
    facilityName: "Kuala Lumpur General Hospital",
    facilityAddress: "Jalan Pahang, 50586 Kuala Lumpur",
    appointmentDate: "2025-08-15",
    appointmentTime: "10:30",
    duration: 45,
    status: "scheduled",
    mode: "physical",
    patientId: "self",
    patientName: "Yourself",
    isForSelf: true,
    symptoms: [
      { id: "sym-001", description: "Chest pain", severity: "moderate", duration: "2 days" },
      { id: "sym-002", description: "Shortness of breath", severity: "mild", duration: "1 week" },
    ],
    reason: "Regular checkup",
    documents: [
      {
        id: "doc-001",
        name: "Previous ECG Results.pdf",
        type: "medical_record",
        uploadDate: "2023-11-28",
        fileSize: "2.4 MB",
        fileUrl: "/sample-file-url.pdf",
      },
    ],
    notes: "Please bring your previous medication list and any other relevant medical documents.",
    createdAt: "2023-11-20",
    updatedAt: "2023-11-20",
  },
  {
    id: "apt-002",
    doctorId: 2,
    doctorName: "Dr. Sarah Wong",
    doctorSpecialty: "Dermatology",
    doctorImage: "/doctor2.jpg",
    facilityId: 4,
    facilityName: "Selangor Health Hub",
    facilityAddress: "15, Jalan SS 12/1A, 47500 Subang Jaya, Selangor",
    appointmentDate: "2025-06-18",
    appointmentTime: "14:00",
    duration: 30,
    status: "scheduled",
    mode: "video",
    patientId: "family-1",
    patientName: "Aisha (Daughter)",
    isForSelf: false,
    symptoms: [{ id: "sym-003", description: "Skin rash", severity: "moderate", duration: "4 days" }],
    reason: "New symptoms",
    documents: [],
    notes: "",
    createdAt: "2023-11-25",
    updatedAt: "2023-11-25",
  },
  {
    id: "apt-003",
    doctorId: 3,
    doctorName: "Dr. Raj Patel",
    doctorSpecialty: "Orthopedics",
    doctorImage: "/doctor3.jpg",
    facilityId: 2,
    facilityName: "Penang Medical Center",
    facilityAddress: "1, Jalan Bukit Merah, 11900 Bayan Lepas, Penang",
    appointmentDate: "2026-02-22",
    appointmentTime: "11:00",
    duration: 60,
    status: "scheduled",
    mode: "physical",
    patientId: "self",
    patientName: "Yourself",
    isForSelf: true,
    symptoms: [
      { id: "sym-004", description: "Back pain", severity: "severe", duration: "2 weeks" },
      { id: "sym-005", description: "Joint pain", severity: "moderate", duration: "10 days" },
    ],
    reason: "Follow-up appointment",
    documents: [
      {
        id: "doc-002",
        name: "X-Ray Report.pdf",
        type: "lab_result",
        uploadDate: "2023-11-30",
        fileSize: "3.2 MB",
        fileUrl: "/sample-file-url.pdf",
      },
    ],
    notes: "",
    createdAt: "2023-11-15",
    updatedAt: "2023-11-30",
  },

  // Past appointments
  {
    id: "apt-004",
    doctorId: 4,
    doctorName: "Dr. Lisa Chen",
    doctorSpecialty: "Pediatrics",
    doctorImage: "/doctor4.jpg",
    facilityId: 3,
    facilityName: "Johor Specialist Clinic",
    facilityAddress: "39, Jalan Harimau, Taman Century, 80250 Johor Bahru",
    appointmentDate: "2023-11-05",
    appointmentTime: "9:00",
    duration: 30,
    status: "completed",
    mode: "video",
    patientId: "family-2",
    patientName: "Amirah (Mother)",
    isForSelf: false,
    symptoms: [
      { id: "sym-006", description: "Fever", severity: "mild", duration: "2 days" },
      { id: "sym-007", description: "Cough", severity: "moderate", duration: "3 days" },
    ],
    reason: "Medication review",
    documents: [
      {
        id: "doc-003",
        name: "Medication Prescription.pdf",
        type: "prescription",
        uploadDate: "2023-11-05",
        fileSize: "1.1 MB",
        fileUrl: "/sample-file-url.pdf",
      },
    ],
    notes: "Follow-up in 2 weeks if symptoms persist.",
    createdAt: "2023-10-25",
    updatedAt: "2023-11-05",
  },
  {
    id: "apt-005",
    doctorId: 5,
    doctorName: "Dr. Mohd Faizal",
    doctorSpecialty: "Neurology",
    doctorImage: "/doctor5.jpg",
    facilityId: 5,
    facilityName: "Ipoh Community Hospital",
    facilityAddress: "20, Jalan Raja Dr Nazrin Shah, 30250 Ipoh, Perak",
    appointmentDate: "2023-10-20",
    appointmentTime: "15:30",
    duration: 45,
    status: "cancelled",
    mode: "physical",
    patientId: "self",
    patientName: "Yourself",
    isForSelf: true,
    symptoms: [
      { id: "sym-008", description: "Headache", severity: "severe", duration: "1 week" },
      { id: "sym-009", description: "Dizziness", severity: "moderate", duration: "3 days" },
    ],
    reason: "Chronic condition management",
    documents: [],
    notes: "",
    createdAt: "2023-10-10",
    updatedAt: "2023-10-18",
  },
  {
    id: "apt-006",
    doctorId: 1,
    doctorName: "Dr. Ahmad Razak",
    doctorSpecialty: "Cardiology",
    doctorImage: "/doctor1.jpg",
    facilityId: 1,
    facilityName: "Kuala Lumpur General Hospital",
    facilityAddress: "Jalan Pahang, 50586 Kuala Lumpur",
    appointmentDate: "2023-09-15",
    appointmentTime: "11:30",
    duration: 60,
    status: "no_show",
    mode: "physical",
    patientId: "family-3",
    patientName: "Rizal (Father)",
    isForSelf: false,
    symptoms: [{ id: "sym-010", description: "Chest pain", severity: "moderate", duration: "1 day" }],
    reason: "New symptoms",
    documents: [],
    notes: "Patient did not show up for the appointment.",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-15",
  },

  // More upcoming appointments
  {
    id: "apt-007",
    doctorId: 2,
    doctorName: "Dr. Sarah Wong",
    doctorSpecialty: "Dermatology",
    doctorImage: "/doctor2.jpg",
    facilityId: 4,
    facilityName: "Selangor Health Hub",
    facilityAddress: "15, Jalan SS 12/1A, 47500 Subang Jaya, Selangor",
    appointmentDate: "2024-01-05",
    appointmentTime: "13:00",
    duration: 30,
    status: "scheduled",
    mode: "physical",
    patientId: "self",
    patientName: "Yourself",
    isForSelf: true,
    symptoms: [{ id: "sym-011", description: "Skin irritation", severity: "mild", duration: "1 week" }],
    reason: "Follow-up appointment",
    documents: [],
    notes: "",
    createdAt: "2023-11-20",
    updatedAt: "2023-11-20",
  },
  {
    id: "apt-008",
    doctorId: 3,
    doctorName: "Dr. Raj Patel",
    doctorSpecialty: "Orthopedics",
    doctorImage: "/doctor3.jpg",
    facilityId: 2,
    facilityName: "Penang Medical Center",
    facilityAddress: "1, Jalan Bukit Merah, 11900 Bayan Lepas, Penang",
    appointmentDate: "2024-03-10",
    appointmentTime: "10:00",
    duration: 45,
    status: "scheduled",
    mode: "video",
    patientId: "family-1",
    patientName: "Aisha (Daughter)",
    isForSelf: false,
    symptoms: [{ id: "sym-012", description: "Ankle pain", severity: "moderate", duration: "3 days" }],
    reason: "New symptoms",
    documents: [],
    notes: "Virtual consultation to assess if in-person visit is needed.",
    createdAt: "2023-11-28",
    updatedAt: "2023-11-28",
  },

  // More past appointments
  {
    id: "apt-009",
    doctorId: 4,
    doctorName: "Dr. Lisa Chen",
    doctorSpecialty: "Pediatrics",
    doctorImage: "/doctor4.jpg",
    facilityId: 3,
    facilityName: "Johor Specialist Clinic",
    facilityAddress: "39, Jalan Harimau, Taman Century, 80250 Johor Bahru",
    appointmentDate: "2023-08-22",
    appointmentTime: "14:30",
    duration: 30,
    status: "completed",
    mode: "physical",
    patientId: "family-2",
    patientName: "Amirah (Mother)",
    isForSelf: false,
    symptoms: [{ id: "sym-013", description: "Sore throat", severity: "mild", duration: "2 days" }],
    reason: "Regular checkup",
    documents: [
      {
        id: "doc-004",
        name: "Medical Summary.pdf",
        type: "medical_record",
        uploadDate: "2023-08-22",
        fileSize: "1.8 MB",
        fileUrl: "/sample-file-url.pdf",
      },
    ],
    notes: "",
    createdAt: "2023-08-10",
    updatedAt: "2023-08-22",
  },
  {
    id: "apt-010",
    doctorId: 5,
    doctorName: "Dr. Mohd Faizal",
    doctorSpecialty: "Neurology",
    doctorImage: "/doctor5.jpg",
    facilityId: 5,
    facilityName: "Ipoh Community Hospital",
    facilityAddress: "20, Jalan Raja Dr Nazrin Shah, 30250 Ipoh, Perak",
    appointmentDate: "2023-07-15",
    appointmentTime: "16:00",
    duration: 60,
    status: "completed",
    mode: "video",
    patientId: "self",
    patientName: "Yourself",
    isForSelf: true,
    symptoms: [{ id: "sym-014", description: "Migraine", severity: "severe", duration: "3 days" }],
    reason: "Chronic condition management",
    documents: [
      {
        id: "doc-005",
        name: "Medication Prescription.pdf",
        type: "prescription",
        uploadDate: "2023-07-15",
        fileSize: "0.8 MB",
        fileUrl: "/sample-file-url.pdf",
      },
      {
        id: "doc-006",
        name: "Brain Scan Results.pdf",
        type: "lab_result",
        uploadDate: "2023-07-10",
        fileSize: "4.2 MB",
        fileUrl: "/sample-file-url.pdf",
      },
    ],
    notes: "Continue with current medication. Follow up in 3 months.",
    createdAt: "2023-07-01",
    updatedAt: "2023-07-15",
  },
];

export default dummyAppointments;
