import { Facility } from "@/app/props";

const dummyFacilities: Facility[] = [
  {
    id: 1,
    name: "Hospital Ampang",
    address: "Hospital Ampang,Jalan Mewah Utara, Taman Pandan Mewah, 68000 Ampang Jaya, Selangor",
    state: "Selangor",
    city: "Ampang Jaya",
    type: "hospital",
    telephone: "03-4289 5000",
    imageUrl: "/icons/facilities/hospital/hospital-ampang.png",
  },
  {
    id: 2,
    name: "Hospital Banting",
    address: "Hospital Banting, Jalan Sultan Alam Shah, 42700 Banting, Selangor",
    state: "Selangor",
    city: "Banting",
    type: "hospital",
    telephone: "03-4289 5000",
    imageUrl: "/icons/facilities//hospital/hospital-banting.png",
  },
  {
    id: 3,
    name: "Clinic Kota Damansara",
    address:
      "Klinik Kesihatan Kota Damansara, No. 58 Tingkat 3, Jalan Pekaka 8/3, Kota Damansara, 47810, Petaling Jaya, Selangor",
    state: "Selangor",
    city: "Petaling Jaya",
    type: "clinic",
    telephone: "03-6140 1026",
    imageUrl: "/icons/facilities/clinic/clinic-kota-damansara.png",
  },
  {
    id: 4,
    name: "Hospital Kuala Kubu Bharu",
    address: "Jalan Hospital Kuala Kubu Bharu, 44000 Kuala Kubu Bharu, Hulu Selangor, Selangor",
    state: "Selangor",
    city: "Hulu Selangor",
    type: "hospital",
    telephone: "03-4289 5000",
    imageUrl: "/icons/facilities/hospital/hospital-kuala-kubu-bharu.png",
  },
  {
    id: 5,
    name: "Clinic Ijok",
    address: "KK Ijok, JKR 1087 Jalan Simpang Tiga, Ijok, 45600, Kuala Selangor, Selangor",
    state: "Selangor",
    city: "Ijok",
    type: "clinic",
    telephone: "03-3279 1167",
    imageUrl: "/icons/facilities/clinic/clinic-ijok.png",
  },
  {
    id: 6,
    name: "Hospital Kuala Lumpur",
    address: "Jalan Pahang, 50586 Kuala Lumpur, Wilayah Persekutuan",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "hospital",
    telephone: "03-2615 5555",
    imageUrl: "/icons/facilities/hospital/hospital-ampang.png",
  },
  {
    id: 7,
    name: "Klinik Kesihatan Putrajaya",
    address: "Presint 9, 62250 Putrajaya, Wilayah Persekutuan",
    state: "Putrajaya",
    city: "Putrajaya",
    type: "clinic",
    telephone: "03-8888 3600",
    imageUrl: "/icons/facilities/clinic/clinic-kota-damansara.png",
  },
  {
    id: 8,
    name: "Subang Jaya Medical Centre",
    address: "1, Jalan SS 12/1A, SS 12, 47500 Subang Jaya, Selangor",
    state: "Selangor",
    city: "Subang Jaya",
    type: "hospital",
    telephone: "03-5639 1212",
    imageUrl: "/icons/facilities/hospital/hospital-banting.png",
  },
  {
    id: 9,
    name: "Pantai Hospital Kuala Lumpur",
    address: "8, Jalan Bukit Pantai, Bangsar, 59100 Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "hospital",
    telephone: "03-2296 0888",
    imageUrl: "/icons/facilities/hospital/hospital-ampang.png",
  },
  {
    id: 10,
    name: "Klinik Pergigian Ampang",
    address: "Jalan Pandan Utama, Pandan Indah, 55100 Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "clinic",
    telephone: "03-4292 1333",
    imageUrl: "/icons/facilities/clinic/clinic-kota-damansara.png",
  },
  {
    id: 11,
    name: "Gleneagles Hospital Kuala Lumpur",
    address: "282 & 286, Jalan Ampang, 50450 Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "hospital",
    telephone: "03-4141 3000",
    imageUrl: "/icons/facilities/hospital/hospital-kuala-kubu-bharu.png",
  },
  {
    id: 12,
    name: "Columbia Asia Hospital - Setapak",
    address: "Lot 33, Jalan Danau Kota, Taman Danau Kota, 53300 Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "hospital",
    telephone: "03-4145 9999",
    imageUrl: "/icons/facilities/hospital/hospital-banting.png",
  },
  {
    id: 13,
    name: "Klinik Kesihatan Cheras",
    address: "Jalan Yaacob Latif, Bandar Tun Razak, 56000 Cheras, Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "clinic",
    telephone: "03-9132 0033",
    imageUrl: "/icons/facilities/clinic/clinic-ijok.png",
  },
  {
    id: 14,
    name: "Prince Court Medical Centre",
    address: "39, Jalan Kia Peng, 50450 Kuala Lumpur",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    type: "hospital",
    telephone: "03-2160 0000",
    imageUrl: "/icons/facilities/hospital/hospital-ampang.png",
  },
  {
    id: 15,
    name: "Klinik Kesihatan Selayang",
    address: "KM 12, Jalan Ipoh, 68100 Selayang, Selangor",
    state: "Selangor",
    city: "Selayang",
    type: "clinic",
    telephone: "03-6126 5800",
    imageUrl: "/icons/facilities/clinic/clinic-kota-damansara.png",
  },
];

export default dummyFacilities;
