import { FamilyMember } from "../../props";

const dummyFamilyMembers: FamilyMember[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    phone: "+60 12-345 6789",
    relationship: "spouse",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    dateAdded: "2023-08-15T08:00:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: true,
      viewMedicalRecords: true,
      managePrescriptions: true,
    },
  },
  {
    id: "2",
    name: "Michael Tan",
    email: "michael.tan@example.com",
    phone: "+60 16-123 4567",
    relationship: "child",
    dateAdded: "2023-09-20T10:30:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: true,
      viewMedicalRecords: false,
      managePrescriptions: false,
    },
  },
  {
    id: "3",
    name: "Siti Aminah",
    email: "siti.aminah@example.com",
    phone: "+60 13-987 6543",
    relationship: "parent",
    profileImage: "https://randomuser.me/api/portraits/women/67.jpg",
    dateAdded: "2023-07-05T14:20:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: true,
      viewMedicalRecords: true,
      managePrescriptions: true,
    },
  },
  {
    id: "4",
    name: "Raj Kumar",
    email: "raj.kumar@example.com",
    phone: "+60 17-765 4321",
    relationship: "sibling",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    dateAdded: "2023-10-12T09:15:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: false,
      viewMedicalRecords: false,
      managePrescriptions: false,
    },
  },
  {
    id: "5",
    name: "Lisa Wong",
    email: "lisa.wong@example.com",
    phone: "+60 19-234 5678",
    relationship: "friend",
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
    dateAdded: "2023-11-08T16:45:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: false,
      viewMedicalRecords: false,
      managePrescriptions: false,
    },
  },
  {
    id: "6",
    name: "Ahmad Zulkifli",
    email: "ahmad.zulkifli@example.com",
    phone: "+60 11-876 5432",
    relationship: "caregiver",
    profileImage: "https://randomuser.me/api/portraits/men/59.jpg",
    dateAdded: "2023-06-22T11:30:00.000Z",
    permissions: {
      appointmentBooking: true,
      appointmentManagement: true,
      viewMedicalRecords: true,
      managePrescriptions: true,
    },
  },
  {
    id: "7",
    name: "Mei Ling Chen",
    email: "meiling.chen@example.com",
    phone: "+60 14-555 6789",
    relationship: "relative",
    dateAdded: "2023-08-30T13:20:00.000Z",
    permissions: {
      appointmentBooking: false,
      appointmentManagement: false,
      viewMedicalRecords: true,
      managePrescriptions: true,
    },
  },
  {
    id: "8",
    name: "Dr. James Wilson",
    email: "dr.wilson@medclinic.org",
    phone: "+60 12-999 8888",
    relationship: "other",
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    dateAdded: "2023-09-05T10:00:00.000Z",
    permissions: {
      appointmentBooking: false,
      appointmentManagement: false,
      viewMedicalRecords: true,
      managePrescriptions: false,
    },
  },
];

export default dummyFamilyMembers;
