import { MedicalRecord } from "@/app/medical-records/props";

export const dummyMedicalRecords: MedicalRecord[] = [
  {
    id: "1",
    name: "Annual Health Checkup Report",
    type: "medical_report",
    category: "system",
    fileType: "pdf",
    uploadDate: "2023-10-15",
    fileSize: "2.4 MB",
    fileUrl: "/sample-url",
    description: "Annual health examination results from Hospital Kuala Lumpur",
    permissions: {
      read: true,
      edit: false,
      download: true,
      share: true,
    },
    sharedWith: [],
  },
  {
    id: "2",
    name: "Prescription for Hypertension",
    type: "prescription",
    category: "system",
    fileType: "pdf",
    uploadDate: "2023-11-10",
    fileSize: "1.2 MB",
    fileUrl: "/sample-url",
    description: "Medication for blood pressure management",
    permissions: {
      read: true,
      edit: false,
      download: true,
      share: true,
    },
    sharedWith: ["family-1"],
  },
  {
    id: "3",
    name: "Dental X-Ray",
    type: "medical_report",
    category: "self-uploaded",
    fileType: "pdf",
    uploadDate: "2023-09-05",
    fileSize: "3.5 MB",
    fileUrl: "/sample-url",
    description: "Dental X-ray from private clinic",
    permissions: {
      read: true,
      edit: true,
      download: true,
      share: true,
    },
    sharedWith: [],
  },
  {
    id: "4",
    name: "Vitamin Supplements Prescription",
    type: "prescription",
    category: "self-uploaded",
    fileType: "pdf",
    uploadDate: "2023-12-20",
    fileSize: "0.8 MB",
    fileUrl: "/sample-url",
    description: "Nutritional supplements recommended by dietitian",
    permissions: {
      read: true,
      edit: true,
      download: true,
      share: false,
    },
    sharedWith: [],
  },
  {
    id: "5",
    name: "Blood Test Results",
    type: "medical_report",
    category: "system",
    fileType: "pdf",
    uploadDate: "2024-01-15",
    fileSize: "1.7 MB",
    fileUrl: "/sample-url",
    description: "Complete blood count and lipid profile",
    permissions: {
      read: true,
      edit: false,
      download: true,
      share: true,
    },
    sharedWith: ["family-2"],
  },
];
