package com.mytelmed.common.constants;

public enum DocumentType {
    PRESCRIPTION,
    LAB_REPORT,
    RADIOLOGY_REPORT,
    DISCHARGE_SUMMARY,
    OPERATIVE_REPORT,
    CONSULTATION_NOTE,
    PROGRESS_NOTE,
    PATHOLOGY_REPORT,
    IMMUNIZATION_RECORD,
    REFERRAL_LETTER,
    MEDICAL_CERTIFICATE,
    HISTORY_AND_PHYSICAL,
    EMERGENCY_ROOM_REPORT,
    ANESTHESIA_RECORD,
    INPATIENT_SUMMARY,
    OUTPATIENT_SUMMARY,
    NURSING_NOTE,
    MENTAL_HEALTH_NOTE,
    MEDICAL_IMAGING,
    CLINICAL_TRIAL_DOCUMENT,
    TREATMENT_PLAN,
    DIAGNOSTIC_REPORT,
    VITAL_SIGNS_RECORD,
    ALLERGY_RECORD,
    OTHER
}
